package UICreator;

import Assistant_Panel.ProfCreatePanel;
import DB.DB_CONNECTER;
import Reservation_Panel.Basic_Reservation_Panel;
import Reservation_Panel.Lecture_Room_Select;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

import javax.swing.JPanel;


public abstract class Content_Panel extends JPanel {
	//ArrayList<JPanel> Panels = new ArrayList<JPanel>();
	//ArrayList<Basic_Reservation_Panel> r = new ArrayList<Basic_Reservation_Panel>();
	//Lecture_Room_Select Selecter = new Lecture_Room_Select();
	Content_Panel() {
		this.setLayout(null);
		// this.setBackground(new Color(255,0,0));
	}

	abstract void Set_Multi_Layout();
}

class Student_Content_Panel extends Content_Panel {
	Student_Content_Panel() {

	}

	@Override
	void Set_Multi_Layout() {
		// TODO Auto-generated method stub
	}

}

class Assistant_Content_Panel extends Content_Panel{

	@Override
	void Set_Multi_Layout() {
		// TODO Auto-generated method stub
	
	}
}



class Professor_Content_Panel extends Content_Panel{

	@Override
	void Set_Multi_Layout() {
		// TODO Auto-generated method stub
		
	}
}

 class reservation_list_panel extends javax.swing.JPanel {

    /**
     * Creates new form reservation_list_Panel
     */
    reservation_list_panel(int sizeX,int sizeY) {
        this.setLayout(null);
        this.setBounds(0,0,sizeX,sizeY);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(806, 576));

        jLabel2.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel2.setText("실습실");

        jLabel3.setFont(new java.awt.Font("나눔고딕", 1, 24)); // NOI18N
        jLabel3.setText("예약관리");

        jTextField1.setText("호실 불러오는 곳");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel4.setText("좌석 번호");

        jTextField2.setText("좌석번호 불러오는 곳");

        jLabel5.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel5.setText("사용시간");

        jButton6.setText("연장");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("반납");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("취소");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel6.setText("~");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "09:00", "10:00", "11:00", "12:00", "13:00", "14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00", "21:00", "22:00", "23:00" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jButton6))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jButton7)
                                        .addGap(30, 30, 30)
                                        .addComponent(jButton8))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(523, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addContainerGap(350, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        JOptionPane.showMessageDialog(null, "예약 연장되었습니다.");

        //만약 예약연장을 할 수 없을 때
        //JOptionPane.showMessageDialog(null, "연장할 수 있는 예약이 없습니다.");
        //실습실 관리자가 되었을 때
        //JOptionPane.showMessageDialog(null, "실습실 관리자가 되었습니다.");
        //만약 시간이 불가능해서 예약연장을 할 수 없을 때
        //JOptionPane.showMessageDialog(null, "해당 시간에는 예약이 불가능합니다.");
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "예약 취소되었습니다.");
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "예약을 취소하시겠습니까?","confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if(result == JOptionPane.YES_OPTION){JOptionPane.showMessageDialog(null, "예약 취소되었습니다.");}

    }                                        

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration                   
}

 class User_modify_panel extends javax.swing.JPanel {

    /**
     * Creates new form user_modify_panel
     */
    public User_modify_panel(int sizeX,int sizeY) {
        this.setLayout(null);
        this.setBounds(0,0,sizeX,sizeY);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(806, 576));

        jLabel2.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel2.setText("이름");

        jLabel3.setFont(new java.awt.Font("나눔고딕", 1, 24)); // NOI18N
        jLabel3.setText("회원정보수정");

        jTextField1.setText("이름불러오는 곳");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel4.setText("전화번호");

        jTextField2.setText("전화번호 불러오는 곳");

        jLabel5.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel5.setText("e-mail");

        jTextField3.setText("이메일 불러오는 곳");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel6.setText("학번");

        jTextField4.setText("학번 불러오는 곳");
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel7.setText("ID");

        jTextField5.setText("ID 불러오는 곳");
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel8.setText("PW");

        jTextField6.setText("변경할 PW 적는 곳 불러오지 않음.");
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton9.setText("완료");
        jButton9.setActionCommand("");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("회원 탈퇴");
        jButton10.setActionCommand("");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField2)
                                    .addComponent(jTextField1)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(35, 35, 35)
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 523, Short.MAX_VALUE)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(242, 242, 242)
                .addComponent(jButton9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jButton10))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addComponent(jButton9)
                .addContainerGap(311, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>                        

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "수정 완료되었습니다.");
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "탈퇴 완료되었습니다.");
    }                                         


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    // End of variables declaration                   
}

class inquiry_panel extends javax.swing.JPanel {

    /**
     * Creates new form inquiry_panel
     */
    inquiry_panel(int sizeX,int sizeY) {
        this.setLayout(null);
        this.setBounds(0,0,sizeX,sizeY);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(806, 576));

        jLabel3.setFont(new java.awt.Font("나눔고딕", 1, 24)); // NOI18N
        jLabel3.setText("신고 및 문의");

        jLabel2.setFont(new java.awt.Font("나눔고딕", 0, 18)); // NOI18N
        jLabel2.setText("내용");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("내용 작성하는 곳");
        jScrollPane2.setViewportView(jTextArea1);

        jButton6.setText("확인");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton6)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, "문의 완료되었습니다.");
    }                                        


    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration                   
}

class Reservation_Panel extends JPanel {
        protected JComboBox SelectLect;
        protected JComboBox SelectStu;
        protected JComboBox StartTime;
        protected JComboBox EndTime;
        protected JButton CheckBtn;
        protected JButton ResetBtn;
        Basic_Reservation_Panel T;
        JPanel ME = this;
        int sizeX;
        int sizeY;
        String[] LectNum={"915","916","918","911"};
        private Color[] LectColor= {new Color(143,121,126),new Color(255,194,181),new Color(255,227,204),new Color(100,108,143),
                                    new Color(145,187,242),new Color(3, 90, 166),new Color(2, 48, 89),new Color(1, 21, 38 ),
                                    new Color(19, 26, 64),new Color(39, 50, 115),new Color(78, 100, 166),new Color(130, 159, 217),
                                    new Color(34, 92, 115),new Color(75, 140, 166),new Color(115, 177, 191 ),new Color(160, 206, 217)};
        String id = null;
       boolean reserve_checking=false;
        //int for_team_btn = 0;
        
        private void NewLect(){
            reserve_checking=false;
            ME.remove(6);
            ME.revalidate(); 
            ME.repaint();
           //   System.out.println(""+SelectLect.getSelectedItem().toString());
            String LectNnmStr = SelectLect.getSelectedItem().toString();
            
            //System.out.println(LectNnmStr);
            String MaxStuStr = SelectStu.getSelectedItem().toString();
            T = new Lecture_Room_Select().getRoom(LectNnmStr);
           // System.out.println("x:"+sizeX+" y:"+sizeY + " 1: " +  LectNnmStr + " 2:"+ MaxStuStr);
            T.setBounds(0,sizeY/20,sizeX, sizeY*19/20);
            T.setSize(sizeX, sizeY*19/20);
	    T.Set_cube();
            T.SetMax(Integer.parseInt(MaxStuStr));
            CheckBtn.setEnabled(true);
            try {
                GetData(LectNnmStr);
            } catch (SQLException ex) {
                Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane b=new JOptionPane("이미 예약된 좌석 입니다.");
                
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
            ME.add(T);
        }
 	Reservation_Panel(String id,int sizeX, int sizeY) {
        this.id = id;
        this.sizeX = sizeX;
        this.sizeY = sizeY;
       // T = new Lecture_Room_Select().getRoom("0");
        setLayout(null);
        //강의실선택
        SelectLect= new JComboBox(LectNum);
        SelectLect.setBounds(0,0,sizeX/4,sizeY/20);
        SelectLect.setSelectedIndex(0);
        this.add(SelectLect);
        SelectLect.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
             NewLect();
       }
  });
        //학생수 선택
        int MaxStu = 5;    
        String[] ComboStr = new String[MaxStu];
        for (int i =1 ;i<=MaxStu; i++)
            ComboStr[i-1] = Integer.toString(i);
        SelectStu= new JComboBox(ComboStr);
        SelectStu.setBounds(sizeX/4,0,sizeX/4,sizeY/20);
        this.add(SelectStu);
        SelectStu.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
               
            String MaxStuStr = SelectStu.getSelectedItem().toString();
            T.SetMax(Integer.parseInt(MaxStuStr));

       }
  });
        
        //시간 선택 수정필요
        int MaxTime = 24;
        String[] TimeStart = new String[MaxTime];
        for (int i =0 ;i<MaxTime; i++)
            TimeStart[i] = Integer.toString(i) + ":00";
        StartTime= new JComboBox(TimeStart);
        StartTime.setBounds(sizeX*2/4,0,sizeX/8,sizeY/20);
        this.add(StartTime);
        
        String[] TimeEnd = new String[MaxTime];
        for (int i =1 ;i<=MaxTime; i++)
            TimeEnd[i-1] = Integer.toString(i) + ":00";
        EndTime= new JComboBox(TimeEnd);
        EndTime.setBounds(sizeX*5/8,0,sizeX/8,sizeY/20);
        this.add(EndTime);
        
        StartTime.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if(TimeCheker())
                StartTime.setSelectedIndex(EndTime.getSelectedIndex());
       }
  });
        EndTime.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            if(TimeCheker())
                StartTime.setSelectedIndex(EndTime.getSelectedIndex());
       }
  });
        
        
        CheckBtn = new JButton("예약");
        
        CheckBtn.setBounds(sizeX*3/4,0,sizeX/8,sizeY/20);
        this.add(CheckBtn);   
        CheckBtn.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
                   // protected JComboBox StartTime;
        //protected JComboBox EndTime;
            String pass = null;
            String All_Values = "";
            String[] Values = 
            {
                pass,
                SelectLect.getSelectedItem().toString(),
                T.buttons2.getFirst().getText(),
                id,
                //null,
                StartTime.getSelectedItem().toString()+":00",
                EndTime.getSelectedItem().toString()+":00",
                "0"
            };
            if(T.buttons2.size()>1){
                   JOptionPane b=new JOptionPane();
                    pass =b.showInputDialog("다중 좌석을 선택하셨습니다.\n예약은 10분간 유지되며 경과 시 본인의 자리를 제외한 자리의 예약은 취소 됩니다.\n팀원들이 입력할 비밀번호를 설정해주세요.");
                    //System.out.println("b :"+);
                    if(pass == null){
                        JOptionPane b2=new JOptionPane("예약이 취소 되었습니다.");
                        NewLect();
                        return ;
                    }
            }
           // String a = "(`passwd`,`lab_id`, `seat_num`, `stu_id`, `start_time`, `end_time`,`seat_status`)";
            for (int i=0;i<T.buttons2.size();i++){
            String insert="INSERT INTO Lab_Seat(`passwd`,`lab_id`, `seat_num`, `stu_id`, `start_time`, `end_time`,`seat_status`) Values(";
            if(i>0){
                insert=",(";
                Values[0] = pass;
                Values[6] = null;
            }
            for (int j =0; j<Values.length; j++){
                Values[2] = T.buttons2.get(i).getText();
                if(Values[j] == null)
                    insert = insert +Values[j] +",";
                else
                    insert = insert + "'" +Values[j] +"',";
            }
            insert = insert.substring(0, insert.length() - 1)+")";
            All_Values = All_Values + insert;
           // T.buttons2.remove();
        }
         All_Values = All_Values+ ";";
                            try {
                    DB_CONNECTER.Update_Qurey( All_Values);
                } catch (SQLException ex) {
                    /*
                try {
                    DB_CONNECTER.Update_Qurey("DELETE FROM Lab_Seat WHERE id='"+id+"';");
                     JOptionPane.showMessageDialog(null, "그 사이에 다른사람이 가져감.");
                } catch (SQLException ex1) {
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex1);
                } catch (ClassNotFoundException ex1) {
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex1);
                }
                    */
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "그 사이에 다른사람이 가져감.");
                    return;
                } catch (ClassNotFoundException ex) {
                   
                    /*
                try {
                    DB_CONNECTER.Update_Qurey("DELETE FROM Lab_Seat WHERE id='"+id+"';");
                      JOptionPane.showMessageDialog(null, "그 사이에 다른사람이 가져감.");
                } catch (SQLException ex1) {
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex1);
                } catch (ClassNotFoundException ex1) {
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex1);
                }
                    */
                    
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
                    JOptionPane.showMessageDialog(null, "그 사이에 다른사람이 가져감.");
                    return;
                }
            System.out.println("try"+1+": "+ All_Values);
            JOptionPane.showMessageDialog(null, "예약되었습니다.");
             NewLect();
             //SelectLect.setSelectedIndex(SelectLect.getSelectedIndex());
             //SelectLect.ac
             /*
            try {
                String Arr[][] = DB_CONNECTER.Exe_Qurey("INSERT INTO ~");
                JOptionPane.showMessageDialog(null, "예약되었습니다.");
                SelectLect.actionPerformed(e);
                
            } catch (SQLException ex) {
                Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
            }*/
}
  });
        
        ResetBtn = new JButton("갱신");
        ResetBtn.setBounds(sizeX*7/8,0,sizeX/8,sizeY/20);
        this.add(ResetBtn); 
        ResetBtn.addActionListener(new ActionListener() {
        public void actionPerformed(ActionEvent e) {
              System.out.println( SelectLect.getSelectedItem().toString());
              NewLect();

       }
  });
        
        T = new Lecture_Room_Select().getRoom(SelectLect.getSelectedItem().toString());
        T.setBounds(0,sizeY/20,sizeX, sizeY*19/20);
        T.setSize(sizeX, sizeY*19/20);
	T.Set_cube();
            try {
                GetData(SelectLect.getSelectedItem().toString());
                //T.setBackground(new Color(125, 255, 125));
            } catch (SQLException ex) {
                Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        this.add(T);
       // this.setBackground(new Color(125, 125, 125));
        this.setSize(sizeX,sizeY);
        this.setVisible(true);
                    }
        private boolean TimeCheker(){
            return (StartTime.getSelectedIndex()>EndTime.getSelectedIndex());
        }
    @SuppressWarnings("empty-statement")
    private void GetData(String LectNum) throws SQLException, ClassNotFoundException {

        //DB_CONNECTER.Exe_Qurey("Select *" + " From where lab_id = '"+LectNum + "';");
        String[][] arr = DB_CONNECTER.Exe_Qurey("Select *" + " From Lab_Seat where lab_id = '" + LectNum + "' ORDER BY stu_id;");
        // System.out.println(arr.length+" "+T.buttons.size());
        // System.out.println(arr[1][2]+" "+arr[2][2]+" "+arr[3][2]+" ");
        String colorid = null;
        if(arr.length > 1)
            colorid =arr[1][3];
        int ColorCount = 0;
        for (int i = 1; i < arr.length; i++) {
            // System.out.print(arr[i][2]+" ");
            for (int j = 0; j < T.buttons.size(); j++) {
                if (arr[i][2].equals(T.buttons.get(j).getText())) {
                    //System.out.println(arr[i][0]);
                    if (!arr[i][0].equals("")) {
                        //for_team_btn = i;
                        if(!colorid.equals(arr[i][3])){ ColorCount++;  colorid = arr[i][3]; }
                        T.buttons.get(j).setBackground(LectColor[ColorCount%LectColor.length]);
                        T.buttons.get(j).addActionListener(new MyListener(arr[i][0],arr[i][2]));
                    } else {
                        T.buttons.get(j).setEnabled(false);
                    }
                }
            }
        }
        String[][] arr2 = DB_CONNECTER.Exe_Qurey("Select stu_id" + " From Lab_Seat;");
        for (int i = 1; i < arr2.length; i++) {
            if (arr2[i][0].equals(id)) {
                CheckBtn.setEnabled(false);
                T.reserve_true();
                reserve_checking=true;
                break;
            }
        }
    }
    class MyListener implements ActionListener {
        // Student_States status ;
        //ArrayList<Buttons> buttons;

        String btn_num;
        String passwd;

        MyListener(String passwd, String btn_num) throws SQLException, ClassNotFoundException {
            this.btn_num = btn_num;
            this.passwd = passwd;
        }

        @Override
        public void actionPerformed(ActionEvent e) {
             String pass =null;
             //T.buttons2.remove();
            if (T.buttons2.size() > 0){
                JOptionPane.showMessageDialog(null, "다른자리선택 중입니다. 선택을 위해 갱신 합니다.");
                //return;
            }
            /*
            else if (reserve_checking == true){
                JOptionPane.showMessageDialog(null, "이미 예약하신 상태 입니다.\n예약취소 후 시도하세요.");
               // return;
            }
            */
            else if(reserve_checking == false){
                JOptionPane b = new JOptionPane();
                pass = b.showInputDialog("비밀번호를 입력하세요.");
            }
            //int for_team_btn_loc = for_team_btn;
           // JOptionPane b = new JOptionPane();
            //String pass = b.showInputDialog("비밀번호를 입력하세요.");
            System.out.println(passwd);
            if (passwd.equals(pass)) {
                String qurey = "UPDATE Lab_Seat SET passwd=null, stu_id='" + id + "',seat_status='0' WHERE seat_num ='" + btn_num + "';";
                try {
                    DB_CONNECTER.Update_Qurey(qurey);
                    NewLect();
                } catch (SQLException ex) {
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Reservation_Panel.class.getName()).log(Level.SEVERE, null, ex);
                }
                JOptionPane.showMessageDialog(null, "예약되었습니다.");
            } else if(pass != null){
                JOptionPane.showMessageDialog(null, "다시확인해주세요.");
               // return;
            }
         NewLect();
        }
    }
}
